pip install pysnooper
export RAY_DEDUP_LOGS=0
math_train_path=data/math/train.parquet
math_test_path=data/math/test.parquet
aime2025_test_path=data/aime2025/test.parquet
amc23_test_path=data/amc23/test.parquet

train_files="['$math_train_path']"
test_files="['$math_test_path', '$aime2025_test_path', '$amc23_test_path']"
max_reward=1.0
add_max_reward_num=1
rollout_num=8
n_gpus_per_node=8
project_name=ex-ngrpo
experiment_name=qwen2.5-math-7b-ngrpo
clip_ratio_low=0.16 # DAPO refine
clip_ratio_high=0.24 # DAPO refine
filter_groups=True # DAPO
filter_strategy=all_correct # DAPO refine
default_local_dir=xxx/$project_name/$experiment_name
default_tensorboard_dir=xxx/$project_name/$experiment_name
kl_coef=0.0
lr=1e-6
model_name=xxx/Qwen__Qwen2.5-Math-7B

python3 -m verl.trainer.main_ppo \
    algorithm.adv_estimator=ngrpo \
    algorithm.max_reward=$max_reward \
    algorithm.add_max_reward_num=$add_max_reward_num \
    algorithm.filter_groups.enable=$filter_groups \
    algorithm.filter_groups.strategy=$filter_strategy \
    data.train_files="$train_files" \
    data.val_files="$test_files" \
    data.train_batch_size=1024 \
    data.max_prompt_length=1024 \
    data.max_response_length=3072 \
    data.filter_overlong_prompts=True \
    data.truncation='error' \
    actor_rollout_ref.model.path=$model_name \
    actor_rollout_ref.actor.optim.lr=$lr \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.actor.use_dynamic_bsz=True \
    actor_rollout_ref.actor.ppo_max_token_len_per_gpu=36000 \
    actor_rollout_ref.rollout.log_prob_max_token_len_per_gpu=48000 \
    actor_rollout_ref.ref.log_prob_max_token_len_per_gpu=48000 \
    actor_rollout_ref.actor.ppo_mini_batch_size=256 \
    actor_rollout_ref.actor.fsdp_config.param_offload=False \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=False \
    actor_rollout_ref.actor.clip_ratio_low=$clip_ratio_low \
    actor_rollout_ref.actor.clip_ratio_high=$clip_ratio_high \
    actor_rollout_ref.rollout.enforce_eager=False \
    actor_rollout_ref.rollout.free_cache_engine=False \
    actor_rollout_ref.rollout.tensor_model_parallel_size=2 \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.7 \
    actor_rollout_ref.rollout.n=$rollout_num \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    trainer.experiment_name=$experiment_name \
    algorithm.kl_ctrl.kl_coef=$kl_coef \
    trainer.critic_warmup=0 \
    trainer.logger=['console','tensorboard'] \
    trainer.logger_dir=$default_tensorboard_dir \
    trainer.default_local_dir=$default_local_dir \
    trainer.project_name=$project_name \
    trainer.n_gpus_per_node=$n_gpus_per_node \
    +trainer.val_before_train=False \
    trainer.nnodes=1 \
    trainer.save_freq=7 \
    trainer.test_freq=7 \
    trainer.total_epochs=20 $@ | grep -v "ANTLR"
